baseline.jar.report.level=persist

junit.debug=true
junit.code.coverage=true

build.exclude.dirs= \
	apps/chat

build.binaries.cache.dir=../liferay-binaries-cache-2020

build.repository.private.username=private
build.repository.private.password=0GgG9J3X42k677H

nodejs.node.env=development

test.skip.tear.down=true